{
    'name': 'Plateau Addons',
    'version': '17.0',
    'author': "Maduka Sopulu",
    'category': 'ERP',
    'summary': 'ODOO Base Extension to customize base modules',
    'depends': [
        'base', 'account', 'account_accountant','account_budget', 
        'documents_spreadsheet', 'currency_rate_live', 
        'company_memo', 'ik_multi_branch'],
    'description': "ODOO Base Extension to customize base modules ",
    "data": [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/jos_mda_branch.xml',
        # 'data/jos_charts_of_account.xml',
        'views/res_base.xml',
        'views/view_import_chart_data.xml', 
        'views/company_memo_view.xml', 
        'views/account_tax_view.xml', 
        'views/account_view.xml', 
        'views/ng_account_budget.xml', 
        'views/account_segment_view.xml', 
        'views/security_rule.xml', 
        'views/economic.xml',
        'views/ng_account_budget_line.xml',
        'data/account_segment.xml', 
        'report/account_report_wizard_view.xml', 
        'report/account_report_template.xml', 
        'report/bank_payment_schedule.xml', 
        'report/budget_certificate.xml', 
        'report/external_payment_bank_schedule.xml', 
        'data/jos_journal_data.xml',
    ],
}
