from . import res_users
from . import company_memo
from . import work_instruction
from . import forward_memo
from . import account_payment
from . import request_line
from . import config_setting
from . import account_account
from . import account_move
from . import purchase_order
from . import stock_picking
from . import hr_employee
from . import document
from . import ir_attachment
from . import stock_location
from . import waybill
from . import sale_order
from . import crm