# -*- coding: utf-8 -*-
{
    'name': 'Advanced Office Memo Application',
    'version': '17.0',
    'author': 'Maach Services',
    'description': """An Odoo Memo application use to send memo / information accross individuals: 
    It can also be used to send requests.""",
    'summary': 'Memo application for Companies etc ',
    'category': 'Base',
    # 'live_test_url': "https://www.youtube.com/watch?v=KEjxieAoGeA&feature=youtu.be",

    'depends': ['base', 'account', 'purchase', 'stock', 'mail', 'hr', 'contacts', 'hr_holidays', 'hr_recruitment', 'documents', 'sale', 'crm'], #, 'account_payment_invoice_online_payment_patch'],
    'data': [
        'security/security_group.xml', 
        'sequence/sequence.xml',
        'views/company_memo_view.xml',
        'views/company_memo_purchase_order_form.xml',
        'views/res_users.xml',
        'views/memo_forward_view.xml',
        'views/memo_config_view.xml',
        'views/account_account_view.xml',
        'views/sale_order_view.xml',
        'views/purchase_order_view.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/document_view.xml',
        'views/document_kanban_view.xml',
        'views/crm_view.xml',
        'views/hr_department_view.xml',
        'views/memo_frame_agreement.xml',
        'wizard/return_memo_wizard_view.xml',
        'wizard/company_memo_form_view.xml',
        'reports/report_memo.xml',
        'reports/work_instruction.xml',
        'reports/work_instruction_item_report.xml',
        'reports/waybill.xml',
        'reports/po_bill.xml',
        'views/assets.xml',
        'security/ir.model.access.csv',
        'data/memo_tag.xml',
        'data/memo_stage.xml',
        'data/memo_type.xml',
        'data/memo_config.xml',
        'data/memo_config_travel_crew_change.xml',
        'data/memo_config_export_clearance_freezone.xml',
        'data/memo_config_export_clearance_standard.xml',
        'data/memo_config_travel_air_business_visa.xml',
        'data/memo_config_travel_air_cablegram.xml',
        'data/memo_config_travel_air_visa_arrival.xml',
        'data/memo_config_travel_extension.xml',
        'data/memo_config_travel_sea.xml',
        'data/cfwd_import_pi_standard.xml',
        'data/cfwd_import_pi_direct.xml',
        'data/cfwd_import_pi_bonded_warehouse.xml',
        'data/ir_cron.xml',
        'wizard/memo_config_duplication_wizard_views.xml',
        'wizard/memo_confirmation.xml',
        'wizard/import_logistic_item.xml',
    ],
    
    'assets': {
        'web.assets_backend': [
        '/memo_dashboard/static/src/components/**/*.js',
        '/memo_dashboard/static/src/components/**/*.xml',
        '/memo_dashboard/static/src/components/**/*.scss',
        ],
        
    },
    'assets': {'web.assets_backend': [
        '/company_memo/static/src/css/style.css', 
        '/company_memo/static/src/js/*.js',
        '/company_memo/static/src/components/**/*.js',
        '/company_memo/static/src/components/**/*.xml',
        # '/company_memo/static/src/js/error_message.js',
        # '/company_memo/static/src/js/hide_function.js',
    ]},
    # 'qweb': [
    #     'static/src/xml/base.xml',
    # ],
    'price': 135.00,
    'sequence': 1,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
}
